/* CLEAR STORE TYPE */
export const CLEAR_STORE = 'CLEAR_STORE';

/* AJAX CALL TYPES */
export const GETTING_CHANNEL_INFO = 'GETTING_CHANNEL_INFO';
export const SEARCHING_CHANNEL = 'SEARCHING_CHANNEL';

export const GETTING_VIDEO_COMMENTS = 'GETTING_VIDEO_COMMENTS';
export const GETTING_COMMENT_REPLIES = 'GETTING_COMMENT_REPLIES';

export const GETTING_ALL_PLAYLISTS = 'GETTING_ALL_PLAYLISTS';
export const GETTING_HEADER_PLAYLISTS = 'GETTING_HEADER_PLAYLISTS';
export const GETTING_PLAYLIST = 'GETTING_PLAYLIST';
export const GETTING_PLAYLIST_INFO = 'GETTING_PLAYLIST_INFO';

export const GETTING_RECENT_UPLOADS_PLAYLIST = 'GETTING_RECENT_UPLOADS_PLAYLIST';
export const GETTING_RECENT_UPLOADS_PLAYLIST_ID = 'GETTING_RECENT_UPLOADS_PLAYLIST_ID';

export const GETTING_MOST_RECENT_UPLOAD = 'GETTING_MOST_RECENT_UPLOAD';
export const GETTING_VIDEO_INFO = 'GETTING_VIDEO_INFO';

/* ACTION SUCCESS TYPES */
export const GET_CHANNEL_INFO_SUCCESS = 'GET_CHANNEL_INFO_SUCCESS';
export const GET_SEARCH_RESULTS_SUCCESS = 'GET_SEARCH_RESULTS_SUCCESS';
export const GET_NEXT_RESULTS_SUCCESS = 'GET_NEXT_RESULTS_SUCCESS';

export const GET_MOST_RECENT_UPLOAD_SUCCESS = 'GET_MOST_RECENT_UPLOAD_SUCCESS';
export const GET_RECENT_UPLOADS_PLAYLIST_ID_SUCCESS = 'GET_RECENT_UPLOADS_PLAYLIST_ID_SUCCESS';
export const GET_RECENT_UPLOADS_PLAYLIST_SUCCESS = 'GET_RECENT_UPLOADS_PLAYLIST_SUCCESS';

export const GET_ALL_PLAYLISTS_SUCCESS = 'GET_ALL_PLAYLISTS_SUCCESS';
export const GET_NEXT_PLAYLISTS_SUCCESS = 'GET_NEXT_PLAYLISTS_SUCCESS';
export const GET_HEADER_PLAYLISTS_SUCCESS = 'GET_HEADER_PLAYLISTS_SUCCESS';
export const GET_PLAYLIST_SUCCESS = 'GET_PLAYLIST_SUCCESS';
export const GET_NEXT_VIDEOS_SUCCESS = 'GET_NEXT_VIDEOS_SUCCESS';
export const GET_PLAYLIST_INFO_SUCCESS = 'GET_PLAYLIST_INFO_SUCCESS';

export const GET_VIDEO_SUCCESS = 'GET_VIDEO_SUCCESS';

export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS';
export const GET_NEXT_COMMENTS_SUCCESS = 'GET_NEXT_COMMENTS_SUCCESS';
export const GET_REPLIES_SUCCESS = 'GET_REPLIES_SUCCESS';
export const GET_NEXT_REPLIES_SUCCESS = 'GET_NEXT_REPLIES_SUCCESS';